package com.jomariabejo.motorph.util;

import com.jomariabejo.motorph.model.Employee;
import com.jomariabejo.motorph.model.Timesheet;

import java.sql.Time;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Utility class for generating test timesheet data in JUnit tests.
 * Generates timesheet entries for employees with 8:00 AM to 5:00 PM (17:00) time range.
 */
public class TimesheetTestDataGenerator {

    private static final LocalTime TIME_IN = LocalTime.of(8, 0); // 8:00 AM
    private static final LocalTime TIME_OUT = LocalTime.of(17, 0); // 5:00 PM (17:00)
    private static final float HOURS_WORKED = 9.0f; // 9 hours from 8 AM to 5 PM
    private static final String DEFAULT_STATUS = "Submitted";

    /**
     * Generates timesheets for all employees for a given date range.
     * Creates timesheets from 8:00 AM to 5:00 PM for each weekday.
     *
     * @param employees List of employees
     * @param startDate Start date (inclusive)
     * @param endDate End date (inclusive)
     * @param includeWeekends Whether to include weekends (default: false)
     * @return List of generated timesheet objects
     */
    public static List<Timesheet> generateTimesheetsForAllEmployees(
            List<Employee> employees,
            LocalDate startDate,
            LocalDate endDate,
            boolean includeWeekends) {

        List<Timesheet> timesheets = new ArrayList<>();
        LocalDate currentDate = startDate;

        while (!currentDate.isAfter(endDate)) {
            DayOfWeek dayOfWeek = currentDate.getDayOfWeek();
            boolean isWeekend = dayOfWeek == DayOfWeek.SATURDAY || dayOfWeek == DayOfWeek.SUNDAY;

            if (includeWeekends || !isWeekend) {
                for (Employee employee : employees) {
                    Timesheet timesheet = createTimesheet(employee, currentDate);
                    timesheets.add(timesheet);
                }
            }

            currentDate = currentDate.plusDays(1);
        }

        return timesheets;
    }

    /**
     * Generates timesheets for all employees for a given date range (weekdays only).
     *
     * @param employees List of employees
     * @param startDate Start date (inclusive)
     * @param endDate End date (inclusive)
     * @return List of generated timesheet objects
     */
    public static List<Timesheet> generateTimesheetsForAllEmployees(
            List<Employee> employees,
            LocalDate startDate,
            LocalDate endDate) {
        return generateTimesheetsForAllEmployees(employees, startDate, endDate, false);
    }

    /**
     * Creates a single timesheet entry for an employee on a specific date.
     * Time In: 8:00 AM, Time Out: 5:00 PM (17:00), Hours Worked: 9.0
     *
     * @param employee The employee
     * @param date The date
     * @return The created timesheet entry
     */
    public static Timesheet createTimesheet(Employee employee, LocalDate date) {
        Timesheet timesheet = new Timesheet();
        timesheet.setEmployeeID(employee);
        timesheet.setDate(date);
        timesheet.setTimeIn(Time.valueOf(TIME_IN));
        timesheet.setTimeOut(Time.valueOf(TIME_OUT));
        timesheet.setHoursWorked(HOURS_WORKED);
        timesheet.setStatus(DEFAULT_STATUS);
        timesheet.setRemarks("Test data - Generated by TimesheetTestDataGenerator");

        return timesheet;
    }

    /**
     * Generates timesheets for a specific employee for a date range.
     *
     * @param employee The employee
     * @param startDate Start date (inclusive)
     * @param endDate End date (inclusive)
     * @param includeWeekends Whether to include weekends
     * @return List of generated timesheet objects
     */
    public static List<Timesheet> generateTimesheetsForEmployee(
            Employee employee,
            LocalDate startDate,
            LocalDate endDate,
            boolean includeWeekends) {

        List<Timesheet> timesheets = new ArrayList<>();
        LocalDate currentDate = startDate;

        while (!currentDate.isAfter(endDate)) {
            DayOfWeek dayOfWeek = currentDate.getDayOfWeek();
            boolean isWeekend = dayOfWeek == DayOfWeek.SATURDAY || dayOfWeek == DayOfWeek.SUNDAY;

            if (includeWeekends || !isWeekend) {
                Timesheet timesheet = createTimesheet(employee, currentDate);
                timesheets.add(timesheet);
            }

            currentDate = currentDate.plusDays(1);
        }

        return timesheets;
    }
}

