module com.jomariabejo.motorph {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.web;
    requires java.naming;
    requires org.controlsfx.controls;
    requires com.dlsc.formsfx;
    requires net.synedra.validatorfx;
    requires org.kordamp.ikonli.javafx;
    requires java.logging;
    requires java.sql;
    requires com.opencsv;
    requires org.apache.pdfbox;
    requires static lombok;
    requires jakarta.persistence;
    requires org.hibernate.orm.core;
    requires atlantafx.base;
    requires jdk.compiler;
    requires java.desktop;
    requires org.kordamp.ikonli.material;
    requires org.kordamp.ikonli.fontawesome5;
    opens com.jomariabejo.motorph to javafx.fxml;
    exports com.jomariabejo.motorph;
    opens com.jomariabejo.motorph.model to org.hibernate.orm.core;
    exports com.jomariabejo.motorph.model;
    opens com.jomariabejo.motorph.repository to org.hibernate.orm.core;
    exports com.jomariabejo.motorph.repository;
    opens com.jomariabejo.motorph.service to org.hibernate.orm.core;
    exports com.jomariabejo.motorph.service;
    opens com.jomariabejo.motorph.controller to javafx.fxml;
    exports com.jomariabejo.motorph.controller;
    opens com.jomariabejo.motorph.controller.nav to javafx.fxml;
    exports com.jomariabejo.motorph.controller.nav;
    opens com.jomariabejo.motorph.controller.role.employee to javafx.fxml;
    exports com.jomariabejo.motorph.controller.role.employee;
    opens com.jomariabejo.motorph.controller.role.systemadministrator to javafx.fxml;
    exports com.jomariabejo.motorph.controller.role.systemadministrator;
    opens com.jomariabejo.motorph.controller.role.hr to javafx.fxml;
    exports com.jomariabejo.motorph.controller.role.hr;
    opens com.jomariabejo.motorph.controller.role.accounting to javafx.fxml;
    exports com.jomariabejo.motorph.controller.role.accounting;
    exports com.jomariabejo.motorph.sampler;
    opens com.jomariabejo.motorph.sampler to javafx.fxml;
}